title: BGforge IElib
email: ielib@bgforge.net
description: IElib documentation
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: BGforgeNet

# Build settings
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-analytics

remote_theme: just-the-docs/just-the-docs@v0.12.0
color_scheme: custom
logo: "/assets/favicon/android-chrome-512x512.png"

search_enabled: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

include:
  - _pages

aux_links:
  "Forum":
    - "https://forums.bgforge.net/viewforum.php?f=35"
  "GitHub":
    - "https://github.com/BGforgeNet/BGforge-MLS-IElib"
  "BGforge":
    - "https://bgforge.net"

jekyll_analytics:
  Matomo:
    url: st.bgforge.net
    siteId: "20"
